"""convert skills fields from text to JSON

Revision ID: 9aee72ed4ae1
Revises: c837a8d28a0c
Create Date: 2026-09-30 09:45:46.559637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9aee72ed4ae1'
down_revision: Union[str, None] = 'c837a8d28a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'required_skills',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('students', 'skills',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'skills',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('jobs', 'required_skills',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
