"""add skills field to student

Revision ID: b02ade3c49c0
Revises: e300ab10e710
Create Date: 2026-09-11 10:44:13.508747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02ade3c49c0'
down_revision: Union[str, None] = 'e300ab10e710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('skills', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'skills')
    # ### end Alembic commands ###
